spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mainproject
    username: ${mysql_Id}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  port: 8080

jwt:
    key: ${JWT_SECRET_KEY}
    access-exp-min: 3
    refresh-exp-min: 30
